//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Composer.Entities
{
    public partial class Audit
    {
        #region Primitive Properties
    
        public string Author_Id
        {
            get;
            set;
        }
    
        public System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public System.DateTime ModifyDate
        {
            get;
            set;
        }
    
        public Nullable<short> CollaboratorIndex
        {
            get;
            set;
        }

        #endregion

    }
}
