//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Composer.Entities
{
    public partial class Collaboration
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid Composition_Id
        {
            get { return _composition_Id; }
            set
            {
                if (_composition_Id != value)
                {
                    if (Composition != null && Composition.Id != value)
                    {
                        Composition = null;
                    }
                    _composition_Id = value;
                }
            }
        }
        private System.Guid _composition_Id;
    
        public virtual string Author_Id
        {
            get { return _author_Id; }
            set { _author_Id = value; }
        }
        private string _author_Id = "\"0\"";
    
        public virtual string Collaborator_Id
        {
            get { return _collaborator_Id; }
            set { _collaborator_Id = value; }
        }
        private string _collaborator_Id = "\"0\"";
    
        public virtual int Index
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string PictureUrl
        {
            get;
            set;
        }
    
        public virtual string Notes
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Composition Composition
        {
            get { return _composition; }
            set
            {
                if (!ReferenceEquals(_composition, value))
                {
                    var previousValue = _composition;
                    _composition = value;
                    FixupComposition(previousValue);
                }
            }
        }
        private Composition _composition;

        #endregion

        #region Association Fixup
    
        private void FixupComposition(Composition previousValue)
        {
            if (previousValue != null && previousValue.Collaborations.Contains(this))
            {
                previousValue.Collaborations.Remove(this);
            }
    
            if (Composition != null)
            {
                if (!Composition.Collaborations.Contains(this))
                {
                    Composition.Collaborations.Add(this);
                }
                if (Composition_Id != Composition.Id)
                {
                    Composition_Id = Composition.Id;
                }
            }
        }

        #endregion

    }
}
