//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaboration
    {
        public Collaboration()
        {
            this.AuthorId = "\"0\"";
            this.CollaboratorId = "\"0\"";
            this.Dispositions = new HashSet<Disposition>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompositionId { get; set; }
        public string AuthorId { get; set; }
        public string CollaboratorId { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public string PictureUrl { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
    
        public virtual Composition Composition { get; set; }
        public virtual ICollection<Disposition> Dispositions { get; set; }
    }
}
