//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        public Composition()
        {
            this.Flags = "00000000";
            this.Staffgroups = new HashSet<Staffgroup>();
            this.Collaborations = new HashSet<Collaboration>();
            this.Verses = new HashSet<Verse>();
            this.Arcs = new HashSet<Arc>();
            this.Dispositions = new HashSet<Disposition>();
            this.Provenance = new Provenance();
            this.Audit = new Audit();
        }
    
        public System.Guid Id { get; set; }
        public int Instrument_Id { get; set; }
        public int Key_Id { get; set; }
        public int TimeSignature_Id { get; set; }
        public string Status { get; set; }
        public short StaffConfiguration { get; set; }
        public string Flags { get; set; }
    
        public Provenance Provenance { get; set; }
        public Audit Audit { get; set; }
    
        public virtual ICollection<Staffgroup> Staffgroups { get; set; }
        public virtual ICollection<Collaboration> Collaborations { get; set; }
        public virtual ICollection<Verse> Verses { get; set; }
        public virtual ICollection<Arc> Arcs { get; set; }
        public virtual ICollection<Disposition> Dispositions { get; set; }
    }
}
