//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDataEntities : DbContext
    {
        public CDataEntities()
            : base("name=CDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chord> Chords { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<Measure> Measures { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Collaboration> Collaborations { get; set; }
        public virtual DbSet<Staffgroup> Staffgroups { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Verse> Verses { get; set; }
        public virtual DbSet<Arc> Arcs { get; set; }
        public virtual DbSet<Disposition> Dispositions { get; set; }
    }
}
