//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Composer.Entities
{
    public partial class CDataEntities : ObjectContext
    {
        public const string ConnectionString = "name=CDataEntities";
        public const string ContainerName = "CDataEntities";
    
        #region Constructors
    
        public CDataEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public CDataEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public CDataEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Chord> Chords
        {
            get { return _chords  ?? (_chords = CreateObjectSet<Chord>("Chords")); }
        }
        private ObjectSet<Chord> _chords;
    
        public ObjectSet<Composition> Compositions
        {
            get { return _compositions  ?? (_compositions = CreateObjectSet<Composition>("Compositions")); }
        }
        private ObjectSet<Composition> _compositions;
    
        public ObjectSet<Measure> Measures
        {
            get { return _measures  ?? (_measures = CreateObjectSet<Measure>("Measures")); }
        }
        private ObjectSet<Measure> _measures;
    
        public ObjectSet<Note> Notes
        {
            get { return _notes  ?? (_notes = CreateObjectSet<Note>("Notes")); }
        }
        private ObjectSet<Note> _notes;
    
        public ObjectSet<Collaboration> Collaborations
        {
            get { return _collaborations  ?? (_collaborations = CreateObjectSet<Collaboration>("Collaborations")); }
        }
        private ObjectSet<Collaboration> _collaborations;
    
        public ObjectSet<Staffgroup> Staffgroups
        {
            get { return _staffgroups  ?? (_staffgroups = CreateObjectSet<Staffgroup>("Staffgroups")); }
        }
        private ObjectSet<Staffgroup> _staffgroups;
    
        public ObjectSet<Staff> Staffs
        {
            get { return _staffs  ?? (_staffs = CreateObjectSet<Staff>("Staffs")); }
        }
        private ObjectSet<Staff> _staffs;
    
        public ObjectSet<Verse> Verses
        {
            get { return _verses  ?? (_verses = CreateObjectSet<Verse>("Verses")); }
        }
        private ObjectSet<Verse> _verses;
    
        public ObjectSet<Arc> Arcs
        {
            get { return _arcs  ?? (_arcs = CreateObjectSet<Arc>("Arcs")); }
        }
        private ObjectSet<Arc> _arcs;

        #endregion

    }
}
