//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.Audit = new Audit();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Chord_Id { get; set; }
        public Nullable<int> Accidental_Id { get; set; }
        public Nullable<int> Instrument_Id { get; set; }
        public short Key_Id { get; set; }
        public short Vector_Id { get; set; }
        public Nullable<short> Octave_Id { get; set; }
        public decimal Duration { get; set; }
        public int Location_X { get; set; }
        public int Location_Y { get; set; }
        public string Pitch { get; set; }
        public short Type { get; set; }
        public Nullable<bool> IsDotted { get; set; }
        public Nullable<double> StartTime { get; set; }
        public Nullable<short> Orientation { get; set; }
        public Nullable<bool> IsSpanned { get; set; }
        public string Status { get; set; }
        public string Foreground { get; set; }
        public string Slot { get; set; }
    
        public Audit Audit { get; set; }
    
        public virtual Chord Chord { get; set; }
    }
}
