//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Composer.Entities
{
    public partial class Provenance
    {
        #region Primitive Properties
    
        public string TitleLine
        {
            get;
            set;
        }
    
        public string FontFamily
        {
            get;
            set;
        }
    
        public string SmallFontSize
        {
            get;
            set;
        }
    
        public string LargeFontSize
        {
            get;
            set;
        }

        #endregion

    }
}
