//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    
    public partial class Provenance
    {
        public string TitleLine { get; set; }
        public string FontFamily { get; set; }
        public string SmallFontSize { get; set; }
        public string LargeFontSize { get; set; }
    }
}
