//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Composer.Entities
{
    public partial class Staffgroup
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid Composition_Id
        {
            get { return _composition_Id; }
            set
            {
                if (_composition_Id != value)
                {
                    if (Composition != null && Composition.Id != value)
                    {
                        Composition = null;
                    }
                    _composition_Id = value;
                }
            }
        }
        private System.Guid _composition_Id;
    
        public virtual int Sequence
        {
            get;
            set;
        }
    
        public virtual Nullable<short> Key_Id
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }
    
        public virtual short Index
        {
            get;
            set;
        }

        #endregion

        #region Complex Properties
    
        public virtual Audit Audit
        {
            get { return _audit; }
            set { _audit = value; }
        }
        private Audit _audit = new Audit();

        #endregion

        #region Navigation Properties
    
        public virtual Composition Composition
        {
            get { return _composition; }
            set
            {
                if (!ReferenceEquals(_composition, value))
                {
                    var previousValue = _composition;
                    _composition = value;
                    FixupComposition(previousValue);
                }
            }
        }
        private Composition _composition;
    
        public virtual ICollection<Staff> Staffs
        {
            get
            {
                if (_staffs == null)
                {
                    var newCollection = new FixupCollection<Staff>();
                    newCollection.CollectionChanged += FixupStaffs;
                    _staffs = newCollection;
                }
                return _staffs;
            }
            set
            {
                if (!ReferenceEquals(_staffs, value))
                {
                    var previousValue = _staffs as FixupCollection<Staff>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStaffs;
                    }
                    _staffs = value;
                    var newValue = value as FixupCollection<Staff>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStaffs;
                    }
                }
            }
        }
        private ICollection<Staff> _staffs;

        #endregion

        #region Association Fixup
    
        private void FixupComposition(Composition previousValue)
        {
            if (previousValue != null && previousValue.Staffgroups.Contains(this))
            {
                previousValue.Staffgroups.Remove(this);
            }
    
            if (Composition != null)
            {
                if (!Composition.Staffgroups.Contains(this))
                {
                    Composition.Staffgroups.Add(this);
                }
                if (Composition_Id != Composition.Id)
                {
                    Composition_Id = Composition.Id;
                }
            }
        }
    
        private void FixupStaffs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Staff item in e.NewItems)
                {
                    item.Staffgroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Staff item in e.OldItems)
                {
                    if (ReferenceEquals(item.Staffgroup, this))
                    {
                        item.Staffgroup = null;
                    }
                }
            }
        }

        #endregion

    }
}
