//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Measures = new HashSet<Measure>();
            this.Arcs = new HashSet<Arc>();
            this.Audit = new Audit();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> Clef_Id { get; set; }
        public short Bar_Id { get; set; }
        public Nullable<short> Key_Id { get; set; }
        public int TimeSignature_Id { get; set; }
        public System.Guid Staffgroup_Id { get; set; }
        public int Sequence { get; set; }
        public string Status { get; set; }
        public short Index { get; set; }
    
        public Audit Audit { get; set; }
    
        public virtual ICollection<Measure> Measures { get; set; }
        public virtual Staffgroup Staffgroup { get; set; }
        public virtual ICollection<Arc> Arcs { get; set; }
    }
}
