//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verse
    {
        public Verse()
        {
            this.Audit = new Audit();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Composition_Id { get; set; }
        public short Index { get; set; }
        public string Text { get; set; }
        public int Sequence { get; set; }
        public string Status { get; set; }
        public Nullable<short> Disposition { get; set; }
        public string UIHelper { get; set; }
    
        public Audit Audit { get; set; }
    
        public virtual Composition Composition { get; set; }
    }
}
